### ISSUE TITLE
Does the plugin support ES6?

### ISSUE THREAD

**Issue by leon78113** [John60676/vuepress-plugin-google-adsense2#3]
Hi, I want to use the plugin in my vuepress 2 with Mr.Hope theme, however I got the error, any solution for this?

Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/@vuepress/utils/dist/index.js from node_modules/vuepress-plugin-google-adsense2/dist/index.js not supported.

Instead change the require of /node_modules/@vuepress/utils/dist/index.js in node_modules/vuepress-plugin-google-adsense2/dist/index.js to a dynamic import() which is available in all CommonJS modules.

    at Object.<anonymous> (/node_modules/vuepress-plugin-google-adsense2/dist/index.js:3:17) {
  code: 'ERR_REQUIRE_ESM'
}
 
你好，我在導入這個插件時，出現上面那個錯誤，想請問這個插件是否有 ES6 版本，謝謝

**Comment by John60676** [comment]
It fix in `vuepress-plugin-google-adsense2@1.0.3`

**Comment by leon78113** [comment]
It works, appreciate.
謝謝你的幫助
